version: "2"
services:
  redis:
    image: "redis:4"
  postgres:
    image: "postgres:9.6"
    environment:
     POSTGRES_PASSWORD: 123456
     POSTGRES_USER: postgres
    volumes:
     - ./scripts/db-init:/docker-entrypoint-initdb.d/
  web:
    build: .
    ports:
     - "80:7777"
    volumes:
     - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    command: bash -c "chmod +x ./scripts/wait_for_it.sh && npm run build && ./scripts/wait_for_it.sh postgres:5432 -- npm run debug"